server:
  port: 8080

storage:
  init:
    file:
      path: init-data.txt

db:
  driver: com.mysql.cj.jdbc.Driver
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl-auto: validate
  show_sql: true
  format_sql: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  enabled: true
  drop-first: true
  contexts: development
  default-schema: gym_crm